;;; prometheus-mode.el --- Major modes for Prometheus files -*- lexical-binding: t; -*-

;; Copyright © 2023, by Peter Hoeg

;; Author: Peter Hoeg (peter@hoeg.com)
;; Created: 2023
;; Version: 0.0.1
;; Keywords: languages
;; Homepage: https://hoeg.com
;; Package-Requires: ((emacs "24.3"))

;; This file is not part of GNU Emacs.

;;; License:

;; You can redistribute this program and/or modify it under the terms of the GNU
;; General Public License version 2.

;;; Commentary:
;;
;; Support for various Prometheus files in Emacs. As of right now, we only support the data/metrics
;; files generated by exporters.

;;; Code:

(require 'rx)

;;;###autoload
(defvar prometheus-mode-line-numbers 't "Enable line numbers by default.")

(require 'prometheus-data-mode)

;;;###autoload
(add-to-list 'magic-mode-alist `(,(rx bol "#" (optional space) (or "HELP" "TYPE") space) . prometheus-data-mode))

(provide 'prometheus-mode)

;; Local Variables:
;; coding: utf-8
;; End:

;;; prometheus-mode.el ends here
